package main

var simplePrompts []string = []string{
	"A serene sunset over a calm lake.",
	"A bustling cityscape at night.",
	"A futuristic metropolis with flying cars.",
	"An enchanted forest with glowing mushrooms.",
	"A cozy cabin in a snowy forest.",
	"A tranquil beach with crystal-clear waters.",
	"A mythical dragon soaring through the clouds.",
	"A steampunk-inspired mechanical city.",
	"A vibrant underwater coral reef.",
	"A majestic mountain range at sunrise.",
	"A medieval castle on a hill.",
	"An alien landscape on an exoplanet.",
	"A whimsical circus with colorful tents.",
	"A magical library filled with ancient books.",
	"A haunted mansion on a foggy night.",
	"A tropical island paradise.",
	"A group of astronauts exploring an alien planet.",
	"A bustling marketplace in Marrakech.",
	"A mystical forest with talking animals.",
	"A tranquil Japanese garden with cherry blossoms.",
	"A secret underwater city.",
	"An ancient Egyptian pyramid at sunset.",
	"A group of wizards casting spells.",
	"A floating city in the sky.",
	"A futuristic space station orbiting Earth.",
	"A Viking longship on a stormy sea.",
	"A safari in the African savannah.",
	"A time-traveling adventure through history.",
	"A hidden cave filled with treasure.",
	"A cyberpunk cityscape with neon lights.",
	"A group of knights battling a dragon.",
	"A beautiful Venetian canal with gondolas.",
	"A surreal dreamscape with floating islands.",
	"A high-tech laboratory with futuristic equipment.",
	"A post-apocalyptic wasteland.",
	"A tranquil lakeside cabin during autumn.",
	"A herd of wild horses running across a plain.",
	"A space colony on Mars.",
	"A bustling Asian street market.",
	"A mystical portal to another world.",
	"A hidden temple deep in the jungle.",
	"A fairytale castle in the clouds.",
	"A group of explorers in a dense rainforest.",
	"A magical underwater city inhabited by mermaids.",
	"A futuristic city skyline with holographic billboards.",
	"A Western cowboy showdown in a dusty town.",
	"A group of adventurers on a pirate ship.",
	"A modern art gallery with abstract sculptures.",
	"A serene countryside landscape with rolling hills.",
	"A world where animals have evolved to be intelligent.",
}

var complexPrompts []string = []string{
	"A bustling Martian colony with transparent domes and intricate underground tunnels",
	"An otherworldly forest filled with bioluminescent flora on an alien planet",
	"A steampunk cityscape with floating airships and intricate clockwork buildings",
	"An underwater metropolis inhabited by humanoid creatures with phosphorescent skin",
	"A cyberpunk dystopia with neon-lit streets and holographic billboards",
	"A Renaissance-era alchemist's laboratory filled with intricate glassware and arcane symbols",
	"A surreal dreamscape where gravity seems to shift in unpredictable ways",
	"An ancient Mayan temple hidden in the heart of a dense jungle",
	"A futuristic space station orbiting a gas giant, surrounded by swirling storms",
	"A post-apocalyptic wasteland with overgrown skyscrapers and mutated wildlife",
	"An underwater cityscape made entirely of coral and inhabited by merfolk",
	"A subterranean world of bioluminescent fungi and crystal formations",
	"A Viking longship sailing through a stormy sea with a kraken lurking below",
	"A Victorian-era library filled with books that come to life",
	"An alien marketplace with bizarre creatures trading exotic goods",
	"A haunted mansion with shifting corridors and ghostly apparitions",
	"A fantasy realm where magic and technology coexist seamlessly",
	"A medieval battle on a fantastical battlefield with mythical creatures",
	"A space explorer's encounter with an intelligent gas giant entity",
	"A city on the back of a colossal, walking turtle",
	"A time-traveling scientist's lab filled with swirling portals",
	"A giant, sentient tree with ancient knowledge etched into its bark",
	"A dragon's lair deep within a treacherous mountain range",
	"A crystalline cave inhabited by sentient, glowing crystals",
	"A spacefaring civilization living within the rings of a gas giant",
	"A futuristic sports arena with holographic players and dynamic terrain",
	"An alternate dimension where physics follows different rules",
	"A celestial city floating in the clouds with gravity-defying architecture",
	"A medieval castle guarded by mechanical knights",
	"A forest of sentient, singing trees",
	"A bustling spaceport on an asteroid hurtling through space",
	"A secret society's underground lair filled with ancient artifacts",
	"A colony on a desert planet powered by massive solar arrays",
	"A cityscape frozen in time with people in mid-air, frozen in action",
	"A microscopic world teeming with strange, alien microorganisms",
	"An interdimensional gateway surrounded by swirling energy",
	"A floating island in the sky inhabited by winged humanoids",
	"A vast, underground network of tunnels built by an ancient civilization",
	"A coral reef city populated by humanoid fish people",
	"A massive, sentient crystal guardian protecting an enchanted forest",
	"A Martian rover exploring a canyon filled with strange rock formations",
	"A futuristic metropolis with skyscrapers that touch the edge of space",
	"A time-traveling detective's office with portals to different eras",
	"A labyrinthine, shifting maze in a parallel dimension",
	"A colony on a frozen exoplanet with ice-covered cities",
	"A library of alien knowledge containing books made of light",
	"A futuristic amusement park with gravity-defying roller coasters",
	"A city in the clouds held aloft by giant, floating balloons",
	"A post-singularity world where AI and humans coexist in harmony",
	"A hidden temple in the Himalayas with mystical guardians and artifacts",
}
